# -*- coding: utf-8 -*-

URL = "https://www.worldometers.info/"

DRIVER_PATH = r""

COUNTERS_ABBR = [
    "curr_world_pop",
    "births_year",
    "births_today",
    "deaths_year",
    "deaths_today",
    "pop_growth_year",
    "pop_growth_today", 
    "public_health_exp",
    "public_edu_exp",
    "public_mil_exp",
    "cars_produced",
    "bicy_produced",
    "comp_produced",
    "new_books_pub",
    "newspp_circul",
    "tv_sold_ww",
    "phones_sold",
    "money_spent_vg",
    "net_uses_today",
    "emails_today",
    "posts_wr_today",
    "tweets_today",
    "gg_serch_today",
    "forest_loss_year",
    "ll_soil_er_year",
    "co2_emiss_year",
    "desert_year",
    "toxic_env_year",
    "under_peop_world",
    "overw_peop_world",
    "obs_peop_world",
    "peop_die_hung",
    "money_sp_obs_dis_usa",
    "money_sp_wgt_loss_usa",
    "water_used_year",
    "deaths_waters_dis",
    "peop_acc_safe_wt",
    "energy_today",
    "non_renble_souc",
    "renble_souc",
    "solar_eng_today",
    "oil_pp_today",
    "oil_left",
    "days_end_oil",
    "nat_gas_left",
    "d_end_nat_gas",
    "coal_left",
    "days_end_coal",
    "dis_deaths_year",
    "flu_deaths_year",
    "dth_chil_5_year",
    "abort_year",
    "dth_moth_birth_year",
    "hiv_aids_infec",
    "dth_by_hiv_aids",
    "dth_by_cancer_year",
    "dth_malaria_year",
    "cigar_smok_today",
    "dth_smok_year",
    "dth_alcohol_year",
    "suic_year",
    "money_ill_drugs_year",
    "traf_acc_fatal_year",
]